# Generated by Django 5.0.5 on 2024-05-27 13:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calorie_count", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="apiresponse",
            name="total_calories",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="apiresponse",
            name="total_fat",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="apiresponse",
            name="total_protein",
            field=models.IntegerField(default=0),
        ),
    ]
