# Generated by Django 5.0.5 on 2024-06-07 06:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "calorie_count",
            "0002_apiresponse_total_calories_apiresponse_total_fat_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="UserList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.TextField()),
                ("password", models.TextField()),
                ("age", models.IntegerField(default=21)),
                ("weight", models.FloatField(default=69.5)),
                ("height", models.FloatField(default=185)),
                ("gender", models.CharField(max_length=1)),
                ("activity", models.TextField()),
                ("goal", models.TextField()),
            ],
        ),
    ]
