# Generated by Django 5.0.5 on 2024-06-11 01:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("calorie_count", "0004_userlist_calorie_target_userlist_fat_target_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.TextField()),
                ("age", models.IntegerField(default=21)),
                ("weight", models.FloatField(default=69.5)),
                ("height", models.FloatField(default=185)),
                ("gender", models.CharField(max_length=1)),
                ("activity", models.TextField()),
                ("goal", models.TextField()),
                ("calorie_target", models.FloatField(default=0)),
                ("protein_target", models.FloatField(default=0)),
                ("fat_target", models.FloatField(default=0)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name="UserList",
        ),
    ]
