# Generated by Django 5.0.5 on 2024-06-12 10:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("calorie_count", "0007_alter_userdetails_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userdetails",
            name="user",
        ),
    ]
